### ISSUE TITLE
waterschadeschatter kan niet omgaan met nan waarden in diepteraster

### ISSUE THREAD

**Issue by jcacosta89** [HHNK/hhnk-research-tools#25]
Voorstel om deze toe te voegen;
regel 39 wss_calculations
index_boven[index_boven==len(xp)] = 1 #TODO nan waarden krijgen een andere waarde mee.

Maar er moet ook gekeken worden naar diepteraster aanmaken. daar komen nu nan waardes in? 
Die maakt ie nu in 
"\\corp.hhnk.nl\data\Hydrologen_data\Data\02.modellen\castricum\03_3di_results\batch_results\Batch\01_downloads\depth_max_piek_glg_T10.tif"

block 54 (min_block_size=2048) geeft rechtsonder nan values

![image](https://github.com/HHNK/hhnk-research-tools/assets/78262040/e7dafdfd-9fcf-4478-a059-fe5e9f0a4aea)

**Comment by wvangerwen** [comment]
@d2hydro waarom staat deze weer open?
