### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by wvangerwen** [HHNK/hhnk-research-tools#54]
Wens om centraal logging te kunnen beheren 
- zelfde opmaak met datetime, loglevel, logmessage
- mogelijk maken om console handler aan/uit te zetten (standaard?)
- loggers van imported libraries aan/uit kunnen zetten (standaard aan/ level?)
- hiermee wil ik de logging in bijvoorbeeld https://github.com/HHNK/hhnk-wis-dashboards ook beheren.
- De logging die hiermee nog aangemaakt moet worden zoals in https://github.com/HHNK/FEWS-WIS-modules/blob/main/TWINpy/Bin/TWIN_get_timeseries.py, zou niet meer nodig moeten zijn om dat allemaal op modulelevel te beheren. Liever centraal hier in hrt.
```python
logging.basicConfig(
    filename=str(logfile_txt),
    level=logging.INFO,
    filemode="w",  # w to overwrite, default is 'a' append
    format="%(levelname)s: %(asctime)s %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)
```

Opzet staat hier op basis van SPOC gemaakt.
#55 

@bastiaan-roos Hoe kunnen we bovenstaande wensen het beste inrichten?

**Comment by bastiaan-roos** [comment]
Opzet in #55 is goed, heb een review toegevoegd.
